 version: 2
 jobs:
    build:
        docker:
               - image: circleci/node:10
        steps:
           - checkout
           - restore_cache:
               keys:
                 - v1-dependencies-{{ checksum "package.json" }}
                    # fallback to using the latest cache if no exact match is found
                 - v1-dependencies-

           - run: yarn install

           - save_cache:
               paths:
                 - node_modules
               key: v1-dependencies-{{ checksum "package.json" }}
          
                
    pruebaHTML:
        docker:
               - image: circleci/node:10
        working_directory: ~/repo

        steps:
          - checkout
          - restore_cache:
              keys:
                - v1-dependencies-{{ checksum "package.json" }}
                # fallback to using the latest cache if no exact match is found
                - v1-dependencies-
          - run: yarn run test
                    
                    
                    
    HTMLservidor-des:
        docker:
               - image: circleci/node:10
        working_directory: ~/repo

           steps:
             - checkout

             # Download and cache dependencies
             - restore_cache:
                 keys:
                   - v1-dependencies-{{ checksum "package.json" }}
                   - v1-dependencies-
             - add_ssh_keys:
                 fingerprints:
                   - "S95:40:36:d5:16:09:57:fe:bf:cc:01:3f:18:d5:5c:a8"
             - run: yarn run build
             - run : ssh -o StrictHostKeyChecking=no ubuntu@54.82.64.39 'sudo rm -r /var/www/html/*'
             - run : ssh -o StrictHostKeyChecking=no ubuntu@54.82.64.39 'sudo chmod 777 /var/www/html'
             - run : scp -o StrictHostKeyChecking=no -r ./build/* ubuntu@54.82.64.39:/var/www/html
             - save_cache:
                 paths:
                   - node_modules
                 key: v1-dependencies-{{ checksum "package.json" }} 


    HTMLproduccion-ser1:
        docker:
               - image: circleci/node:10
        working_directory: ~/repo

        steps:
          - checkout
          # Download and cache dependencies
          - restore_cache:
              keys:
                - v1-dependencies-{{ checksum "package.json" }}
                - v1-dependencies-
          - add_ssh_keys:
              fingerprints:
                   - "S95:40:36:d5:16:09:57:fe:bf:cc:01:3f:18:d5:5c:a8"
          - run: yarn run build
          - run : ssh -o StrictHostKeyChecking=no ubuntu@3.223.140.45 'sudo rm -r /var/www/html/*'
          - run : ssh -o StrictHostKeyChecking=no ubuntu@3.223.140.45 'sudo chmod 777 /var/www/html'
          - run : scp -o StrictHostKeyChecking=no -r ./build/* ubuntu@3.223.140.45:/var/www/html          

          - save_cache:
              paths:
                - node_modules
              key: v1-dependencies-{{ checksum "package.json" }}  

    HTMLproduccion-ser2:
        docker:
               - image: circleci/node:10
        working_directory: ~/repo

        steps:
          - checkout
          # Download and cache dependencies
          - restore_cache:
              keys:
                - v1-dependencies-{{ checksum "package.json" }}
                - v1-dependencies-
          - add_ssh_keys:
              fingerprints:
                   - "S95:40:36:d5:16:09:57:fe:bf:cc:01:3f:18:d5:5c:a8"
          - run: yarn run build
          - run : ssh -o StrictHostKeyChecking=no ubuntu@3.95.152.120 'sudo rm -r /var/www/html/*'
          - run : ssh -o StrictHostKeyChecking=no ubuntu@3.95.152.120 'sudo chmod 777 /var/www/html'
          - run : scp -o StrictHostKeyChecking=no -r ./build/* ubuntu@3.95.152.120:/var/www/html          

          - save_cache:
              paths:
                - node_modules
              key: v1-dependencies-{{ checksum "package.json" }}                     
                    
                    
workflows:
  version: 2
  normal_run:
    jobs:
      - build: 
          filters:
            branches:
              only:
                - develop
      - pruebaHTML:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
      - HTMLservidor-des:
          requires:
            - build
            - pruebaHTML
          filters:
            branches:
              only:
                - develop
      - aprovacion:
          type: approval
          requires:
            - HTMLservidor-des
            - pruebaHTML
      - HTMLproduccion-ser1:
          requires:
            - aprovacion
          filters:
            branches:
              only:
                - develop    
      - HTMLproduccion-ser2:
          requires:
            - aprovacion
          filters:
            branches:
              only:
                - develop                       

        