 version: 2
 jobs:
   build:
     docker:
       - image: circleci/node:10
     steps:
       - checkout
       - run: 
            name: "source build"
            command: |
                echo "A first hello"
                ls
                echo "mensaje 2"
                pwd
                scp ../index.html 52.90.108.25:/var/www/html/